version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - type: volume
        source: esdata1
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.4
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  g42_app:
    container_name: g42_app
    image: hisrarul/g42_app:v1
    restart: always
    environment:
      - URL=http://elasticsearch:9200
      - INDEX_NAME='cities'
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
      - kibana
volumes:
  esdata1:
